// Code generated by goctl. DO NOT EDIT.
package types

type SearchRequest struct {
	OrderID string `form:"orderID"`
}

type SearchResponse struct {
	Message  string `json:"message"`
	OrderID  string `json:"orderID"`
	Username string `json:"username"`
	Status   int    `json:"status"`
}
